on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    branches: [ master ]

jobs:
  Build-CC:
    runs-on: ubuntu-latest
    steps:
    - name: Download, configure and install gtest
      run: |
        wget https://github.com/google/googletest/archive/release-1.10.0.tar.gz
        tar xf release-1.10.0.tar.gz
        cd googletest-release-1.10.0
        cmake -DBUILD_SHARED_LIBS=OFF .
        sudo make install

    - name: Checkout the project
      uses: actions/checkout@v2

    - name: Build
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="-Werror" ..
        make
    - name: Save Build Result
        uses: actions/upload-artifact@v3
        if: !failure()
        with:
          name: build
          path: ./build
  C-Test:
    runs-on: ubuntu-latest
    steps:
    - name: load dist
      uses: actions/download-artifact@v2
      with:
        name: build
    - name: Google Test
      run: |
        /home/runner/work/GitHub_Actions_Example/GitHub_Actions_Example/build/test/github_actions_gtest_example.test
  
  Build-C:
    runs-on: ubuntu-latest
    steps:
    - name: Download, configure and install gtest
      run: |
        pwd
        wget https://github.com/google/googletest/archive/release-1.10.0.tar.gz
        tar xf release-1.10.0.tar.gz
        sudo cp -rf googletest-release-1.10.0 /usr/local
        cd googletest-release-1.10.0
        cmake -DBUILD_SHARED_LIBS=OFF .
        sudo make install

    - name: Checkout the project
      uses: actions/checkout@v2

    - name: Build & Google Test
      run: |
        ls /usr/local
        cd src/func1
        make
  
