on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    branches: [ master ]

jobs:
  Build-CC:
    runs-on: ubuntu-latest
    steps:
    - name: Download, configure and install gtest
      run: |
        wget https://github.com/google/googletest/archive/release-1.10.0.tar.gz
        tar xf release-1.10.0.tar.gz
        cd googletest-release-1.10.0
        cmake -DBUILD_SHARED_LIBS=OFF .
        sudo make install
    - name: Checkout the project
      uses: actions/checkout@v2
